<?php
/**
 * Created by PhpStorm.
 * User: 约伯
 * Date: 2018/10/8
 * Time: 14:00
 */

namespace app\index\controller;


use think\Controller;

class Common extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cate=$this->getcate();
        //获取当前所访问一级栏目标识
        $currcontroller=request()->controller();
        $currtype=$this->getcurrtype($currcontroller);
        $this->assign('cate',$cate);
        $this->assign('currtype',$currtype);

        $cateGory=db("category")->where('pid','0')->select();

        $logo=db('config')->select();
        $logoPic=json_decode($logo[0]["config"],true);
        $this->assign([

            'logoPic'=>$logoPic,
            'cateGory'=>$cateGory
        ]);
    }

    private function getcate()
    {
        $res=db('category')->where('pid',0)->order('sort desc,id Asc')->field('id,name,type')->select();
        foreach($res as $k=>$v){
            $res_child=db('category')->where('pid',$v['id'])->order('sort desc,id Asc')->field('id,name,type')->select();
            $res[$k]['child']=$res_child;
        }
        return $res;
    }
    private function getcurrtype($controller)
    {
            switch ($controller){
                case 'Index':
                    return 3;
                case 'Story':
                    return 1;
                case 'Show':
                    return 2;
            }
    }
}